### ISSUE TITLE
ModuleNotFoundError: No module named 'pretrainedmodels'

### ISSUE THREAD

**Issue by handsomefengfeng** [JaryHuang/SSD_FPN_GIoU#19]
我下载了您github中的预训练模型，应该放在哪里呢？

输入`python tools/train.py`后报错

Traceback (most recent call last):
  File "tools/train.py", line 4, in <module>
    from model import build_ssd
  File "/root/yyf/awesome_SSD_FPN_GIoU-master/model/__init__.py", line 1, in <module>
    from .build_ssd import build_ssd
  File "/root/yyf/awesome_SSD_FPN_GIoU-master/model/build_ssd.py", line 10, in <module>
    from model.backbone import Backbone
  File "/root/yyf/awesome_SSD_FPN_GIoU-master/model/backbone/__init__.py", line 1, in <module>
    from .build_backbone import Backbone 
  File "/root/yyf/awesome_SSD_FPN_GIoU-master/model/backbone/build_backbone.py", line 1, in <module>
    import pretrainedmodels
ModuleNotFoundError: No module named 'pretrainedmodels'

**Comment by handsomefengfeng** [comment]
我以为是导入模块 没想到是需要下载的包 T T
