### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by chennaikai11** [JaryHuang/SSD_FPN_GIoU#23]
when i train voc , it has been come.
Traceback (most recent call last):
  File "R:/SSD giou/awesome_SSD_FPN_GIoU-master/tools/train.py", line 278, in <module>
    train()
  File "R:/SSD giou/awesome_SSD_FPN_GIoU-master/tools/train.py", line 89, in train
    parser.error('Must specify dataset_root if specifying dataset')
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 2519, in error
    self.print_usage(_sys.stderr)
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 2489, in print_usage
    self._print_message(self.format_usage(), file)
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 2455, in format_usage
    return formatter.format_help()
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 282, in format_help
    help = self._root_section.format_help()
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 213, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 213, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 320, in _format_usage
    action_usage = format(optionals + positionals, groups)
  File "R:\anaconda\envs\SSD\lib\argparse.py", line 395, in _format_actions_usage
    start = actions.index(group._group_actions[0])
IndexError: list index out of range

**Comment by bellzhong677** [comment]
Hello, I met the same problem as you, how did you solve it
